import homeImg1 from '../assets/CatalogImgs/catalog1/homeImg1.jpg'
import homeImg2 from '../assets/CatalogImgs/catalog1/homeImg2.jpg'
import homeImg3 from '../assets/CatalogImgs/catalog1/homeImg3.jpg'
import planImg1 from '../assets/CatalogImgs/catalog1/planImg1.jpg'
import planImg2 from '../assets/CatalogImgs/catalog1/planImg2.jpg'

export const catalog = [
    {
        id: 0,
        name: 'home',
        area: '36²',
        description: 'это очень хороший дом',
        detailDescription: 'Перед началом любого строительства проводят выбор площадки для будущего строительства объекта. Прежде чем начинать строительство обязательно следует проводить геодезические изыскания. Их перечень довольно широк и содержит горнопроходческие, геофизические буровые и лабораторные работы.',
        homeImg1: homeImg1,
        homeImg2: homeImg2,
        homeImg3: homeImg3,
        planImg1: planImg1,
        planImg2: planImg2,
    },
    {
        id: 1,
        name: 'home',
        area: '36²',
        description: 'это очень хороший дом',
        detailDescription: 'Перед началом любого строительства проводят выбор площадки для будущего строительства объекта. Прежде чем начинать строительство обязательно следует проводить геодезические изыскания. Их перечень довольно широк и содержит горнопроходческие, геофизические буровые и лабораторные работы.',
        homeImg1: homeImg1,
        homeImg2: homeImg2,
        homeImg3: homeImg3,
        planImg1: planImg1,
        planImg2: planImg2,
    },
    {
        id: 2,
        name: 'home',
        area: '36²',
        description: 'это очень хороший дом',
        detailDescription: 'Перед началом любого строительства проводят выбор площадки для будущего строительства объекта. Прежде чем начинать строительство обязательно следует проводить геодезические изыскания. Их перечень довольно широк и содержит горнопроходческие, геофизические буровые и лабораторные работы.',
        homeImg1: homeImg1,
        homeImg2: homeImg2,
        homeImg3: homeImg3,
        planImg1: planImg1,
        planImg2: planImg2,
    },
    {
        id: 3,
        name: 'home',
        area: '36²',
        description: 'это очень хороший дом',
        detailDescription: 'Перед началом любого строительства проводят выбор площадки для будущего строительства объекта. Прежде чем начинать строительство обязательно следует проводить геодезические изыскания. Их перечень довольно широк и содержит горнопроходческие, геофизические буровые и лабораторные работы.',
        homeImg1: homeImg1,
        homeImg2: homeImg2,
        homeImg3: homeImg3,
        planImg1: planImg1,
        planImg2: planImg2,
    },
    {
        id: 4,
        name: 'home',
        area: '36²',
        description: 'это очень хороший дом',
        detailDescription: 'Перед началом любого строительства проводят выбор площадки для будущего строительства объекта. Прежде чем начинать строительство обязательно следует проводить геодезические изыскания. Их перечень довольно широк и содержит горнопроходческие, геофизические буровые и лабораторные работы.',
        homeImg1: homeImg1,
        homeImg2: homeImg2,
        homeImg3: homeImg3,
        planImg1: planImg1,
        planImg2: planImg2,
    },
    {
        id: 5,
        name: 'home',
        area: '36²',
        description: 'это очень хороший дом',
        detailDescription: 'Перед началом любого строительства проводят выбор площадки для будущего строительства объекта. Прежде чем начинать строительство обязательно следует проводить геодезические изыскания. Их перечень довольно широк и содержит горнопроходческие, геофизические буровые и лабораторные работы.',
        homeImg1: homeImg1,
        homeImg2: homeImg2,
        homeImg3: homeImg3,
        planImg1: planImg1,
        planImg2: planImg2,
    },
    {
        id: 6,
        name: 'home',
        area: '36²',
        description: 'это очень хороший дом',
        detailDescription: 'Перед началом любого строительства проводят выбор площадки для будущего строительства объекта. Прежде чем начинать строительство обязательно следует проводить геодезические изыскания. Их перечень довольно широк и содержит горнопроходческие, геофизические буровые и лабораторные работы.',
        homeImg1: homeImg1,
        homeImg2: homeImg2,
        homeImg3: homeImg3,
        planImg1: planImg1,
        planImg2: planImg2,
    },
    {
        id: 7,
        name: 'home',
        area: '36²',
        description: 'это очень хороший дом',
        detailDescription: 'Перед началом любого строительства проводят выбор площадки для будущего строительства объекта. Прежде чем начинать строительство обязательно следует проводить геодезические изыскания. Их перечень довольно широк и содержит горнопроходческие, геофизические буровые и лабораторные работы.',
        homeImg1: homeImg1,
        homeImg2: homeImg2,
        homeImg3: homeImg3,
        planImg1: planImg1,
        planImg2: planImg2,
    },
]